#version: 3.3 opcional desde la verison 1.27.0 de Docker.

#En cuanto a la image, puedes omitir latest o en su defecto seleccionar la versión que buscas:
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - ${DB_PORT_PG}:${DB_PORT_INTERNAL_PG}
        expose:
            - '5432'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
                    - ./postgres_data:/var/lib/postgresql/data

    mysql:
        image: mysql
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT_INTERNAL_MY}
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./mysql_data:/var/lib/mysql
